"use server";
// omnis-ui/app/onboarding/actions.ts
// Onboarding Server Actions — org creation and org join flows.
//
// CONSTITUTION LAW II: Session verified server-side on every invocation.
// The service-role admin client is used to write to public.users (which has
// RLS enabled and only permits service_role INSERT). The user's JWT from the
// anon client is used solely for identity verification — never for DB writes.
//
// public_key: generated as a crypto UUID (v4) server-side. This is a
// placeholder key for the deferred-profile state. A full Ed25519 keypair
// rotation can be added in a future migration once the key management UI
// is built. The constraint is satisfied immediately.
//
// RBAC: After org assignment, a user_roles row is inserted with the selected
// role. Org creators default to qa_manager; joiners explicitly select their role.

import { redirect } from "next/navigation";
import { createClient } from "@/utils/supabase/server";
import { adminClient } from "@/utils/supabase/admin";

// Valid RBAC roles — must match the CHECK constraint in user_roles
export type UserRole = "admin" | "qa_manager" | "developer" | "viewer";

// ---------------------------------------------------------------------------
// Shared result type
// ---------------------------------------------------------------------------

export interface OnboardingResult {
  success: boolean;
  error?: string;
}

// ---------------------------------------------------------------------------
// insertUserRole — shared helper
// ---------------------------------------------------------------------------
// Writes a row into public.user_roles after the org assignment succeeds.
// Returns true on success, false on failure so callers can decide whether to
// roll back. For org creation this MUST succeed — a creator without an 'admin'
// role row is stuck as "pending" with no Team Management rights.
// ---------------------------------------------------------------------------

async function insertUserRole(
  userId: string,
  orgId: string,
  role: UserRole,
): Promise<boolean> {
  const { error } = await adminClient
    .from("user_roles")
    .upsert(
      { user_id: userId, org_id: orgId, role },
      { onConflict: "user_id,org_id", ignoreDuplicates: false },
    );

  if (error) {
    console.error("insertUserRole: failed to write user_roles:", error.message);
    return false;
  }
  return true;
}

// ---------------------------------------------------------------------------
// createOrganization
// ---------------------------------------------------------------------------
// 1. Verifies the authenticated session.
// 2. Validates the company name.
// 3. Inserts a new row into public.organizations via the admin client.
// 4. Updates public.users with the new org_id and a generated public_key.
// 5. Inserts a user_roles row — org creators are always QA Manager.
// 6. Redirects to /dashboard on success.
// ---------------------------------------------------------------------------

export async function createOrganization(
  formData: FormData,
): Promise<OnboardingResult> {
  // Step 1: Verify session.
  const supabase = await createClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: "Unauthorized: valid session required." };
  }

  // Step 2: Validate input.
  const companyName = (formData.get("company_name") as string | null)?.trim();
  if (!companyName || companyName.length < 2) {
    return {
      success: false,
      error: "Company name must be at least 2 characters.",
    };
  }
  if (companyName.length > 120) {
    return { success: false, error: "Company name must be 120 characters or fewer." };
  }

  // Step 3: Create the organization. org_id is a UUID generated by Postgres
  // (gen_random_uuid() is not set as a default in the schema, so we generate
  // it here using the crypto API available in the Next.js runtime).
  const newOrgId = crypto.randomUUID();

  const { error: orgError } = await adminClient
    .from("organizations")
    .insert({ org_id: newOrgId, company_name: companyName });

  if (orgError) {
    console.error("createOrganization: insert org error:", orgError.message);
    return {
      success: false,
      error: "Failed to create organization. Please try again.",
    };
  }

  // Step 4: Upsert the user's profile row with the new org_id and a
  // generated public_key placeholder (UUID v4).
  //
  // We UPSERT (not UPDATE) because the deferred-profile-creation trigger may
  // not have written the public.users row yet for this account. A plain
  // .update() against a missing row silently affects 0 rows, after which the
  // user_roles INSERT below fails its FK constraint — leaving the creator
  // stuck as "pending" with no admin role. Upserting guarantees the profile
  // row exists before we stamp the role.
  const publicKey = crypto.randomUUID();

  const { error: userError } = await adminClient
    .from("users")
    .upsert(
      {
        user_id: user.id,
        developer_email: user.email ?? "",
        org_id: newOrgId,
        public_key: publicKey,
      },
      { onConflict: "user_id", ignoreDuplicates: false },
    );

  if (userError) {
    console.error("createOrganization: upsert user error:", userError.message);
    // Roll back the organization row to avoid orphaned records.
    await adminClient
      .from("organizations")
      .delete()
      .eq("org_id", newOrgId);
    return {
      success: false,
      error: "Failed to assign organization to your profile. Please try again.",
    };
  }

  // Step 5: Assign role. Org creators are always Admin — they own the
  // workspace and need full team management + approval permissions from day
  // one. This write MUST succeed; if it fails the creator would land in the
  // dashboard with no role and be treated as "pending", unable to manage their
  // own team. We therefore treat a role-write failure as fatal and roll back.
  const roleWritten = await insertUserRole(user.id, newOrgId, "admin");

  if (!roleWritten) {
    // Roll back both the profile org assignment and the organization row so
    // the user can retry cleanly instead of being stranded in a half-created
    // state.
    await adminClient
      .from("users")
      .update({ org_id: null })
      .eq("user_id", user.id);
    await adminClient
      .from("organizations")
      .delete()
      .eq("org_id", newOrgId);
    return {
      success: false,
      error: "Failed to assign your admin role. Please try again.",
    };
  }

  // Step 6: Redirect to the dashboard directly.
  // DEMO MODE: Stripe paywall is disabled. Org creators go straight to the
  // dashboard without completing a Stripe checkout.
  // TODO: Re-enable redirect("/pricing") post-demo when billing is reactivated.
  redirect("/dashboard");
}

// ---------------------------------------------------------------------------
// joinOrganization
// ---------------------------------------------------------------------------
// 1. Verifies the authenticated session.
// 2. Validates the enterprise code (treated as an org_id UUID) and role.
// 3. Checks the organization exists in public.organizations.
// 4. Updates the user's row with the existing org_id and a generated public_key.
// 5. Inserts a user_roles row with the selected role.
// 6. Redirects to /dashboard on success.
// ---------------------------------------------------------------------------

export async function joinOrganization(
  formData: FormData,
): Promise<OnboardingResult> {
  // Step 1: Verify session.
  const supabase = await createClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: "Unauthorized: valid session required." };
  }

  // Step 2: Validate the enterprise code.
  const enterpriseCode = (
    formData.get("enterprise_code") as string | null
  )?.trim();

  if (!enterpriseCode) {
    return { success: false, error: "Enterprise code is required." };
  }

  // Basic UUID format validation — prevents a malformed string from hitting
  // the database. Does not replace the existence check below.
  const uuidRegex =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (!uuidRegex.test(enterpriseCode)) {
    return {
      success: false,
      error: "Invalid enterprise code format. Please check the code and try again.",
    };
  }

  // Validate role selection
  const selectedRole = (formData.get("role") as string | null)?.trim() as UserRole | null;
  const validRoles: UserRole[] = ["admin", "qa_manager", "developer", "viewer"];
  if (!selectedRole || !validRoles.includes(selectedRole)) {
    return { success: false, error: "Please select a valid role before joining." };
  }

  // Step 3: Verify the organization exists.
  const { data: org, error: orgError } = await adminClient
    .from("organizations")
    .select("org_id, company_name")
    .eq("org_id", enterpriseCode)
    .single();

  if (orgError || !org) {
    // Return a generic message — do not reveal whether the org_id exists
    // in the system (prevents enumeration attacks).
    return {
      success: false,
      error: "Organization not found. Please check the enterprise code.",
    };
  }

  // Step 4: Update the user's profile.
  const publicKey = crypto.randomUUID();

  const { error: userError } = await adminClient
    .from("users")
    .update({ org_id: org.org_id, public_key: publicKey })
    .eq("user_id", user.id);

  if (userError) {
    console.error("joinOrganization: update user error:", userError.message);
    return {
      success: false,
      error: "Failed to join organization. Please try again.",
    };
  }

  // Step 5: Insert the user's selected role.
  await insertUserRole(user.id, org.org_id, selectedRole);

  // Step 6: Redirect to dashboard.
  redirect("/dashboard");
}
