"use server";
// omnis-ui/app/onboarding/actions.ts
// Onboarding Server Actions — org creation and org join flows.
//
// CONSTITUTION LAW II: Session verified server-side on every invocation.
// The service-role admin client is used to write to public.users (which has
// RLS enabled and only permits service_role INSERT). The user's JWT from the
// anon client is used solely for identity verification — never for DB writes.
//
// public_key: generated as a crypto UUID (v4) server-side. This is a
// placeholder key for the deferred-profile state. A full Ed25519 keypair
// rotation can be added in a future migration once the key management UI
// is built. The constraint is satisfied immediately.

import { redirect } from "next/navigation";
import { createClient } from "@/utils/supabase/server";
import { adminClient } from "@/utils/supabase/admin";

// ---------------------------------------------------------------------------
// Shared result type
// ---------------------------------------------------------------------------

export interface OnboardingResult {
  success: boolean;
  error?: string;
}

// ---------------------------------------------------------------------------
// createOrganization
// ---------------------------------------------------------------------------
// 1. Verifies the authenticated session.
// 2. Validates the company name.
// 3. Inserts a new row into public.organizations via the admin client.
// 4. Updates public.users with the new org_id and a generated public_key.
// 5. Redirects to /dashboard on success.
// ---------------------------------------------------------------------------

export async function createOrganization(
  formData: FormData,
): Promise<OnboardingResult> {
  // Step 1: Verify session.
  const supabase = await createClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: "Unauthorised: valid session required." };
  }

  // Step 2: Validate input.
  const companyName = (formData.get("company_name") as string | null)?.trim();
  if (!companyName || companyName.length < 2) {
    return {
      success: false,
      error: "Company name must be at least 2 characters.",
    };
  }
  if (companyName.length > 120) {
    return { success: false, error: "Company name must be 120 characters or fewer." };
  }

  // Step 3: Create the organisation. org_id is a UUID generated by Postgres
  // (gen_random_uuid() is not set as a default in the schema, so we generate
  // it here using the crypto API available in the Next.js runtime).
  const newOrgId = crypto.randomUUID();

  const { error: orgError } = await adminClient
    .from("organizations")
    .insert({ org_id: newOrgId, company_name: companyName });

  if (orgError) {
    console.error("createOrganization: insert org error:", orgError.message);
    return {
      success: false,
      error: "Failed to create organisation. Please try again.",
    };
  }

  // Step 4: Update the user's profile row with the new org_id and a
  // generated public_key placeholder (UUID v4).
  const publicKey = crypto.randomUUID();

  const { error: userError } = await adminClient
    .from("users")
    .update({ org_id: newOrgId, public_key: publicKey })
    .eq("user_id", user.id);

  if (userError) {
    console.error("createOrganization: update user error:", userError.message);
    // Roll back the organisation row to avoid orphaned records.
    await adminClient
      .from("organizations")
      .delete()
      .eq("org_id", newOrgId);
    return {
      success: false,
      error: "Failed to assign organisation to your profile. Please try again.",
    };
  }

  // Step 5: Redirect to the dashboard. redirect() throws internally in
  // Next.js, so it must not be called inside a try/catch block.
  redirect("/dashboard");
}

// ---------------------------------------------------------------------------
// joinOrganization
// ---------------------------------------------------------------------------
// 1. Verifies the authenticated session.
// 2. Validates the enterprise code (treated as an org_id UUID).
// 3. Checks the organisation exists in public.organizations.
// 4. Updates the user's row with the existing org_id and a generated public_key.
// 5. Redirects to /dashboard on success.
// ---------------------------------------------------------------------------

export async function joinOrganization(
  formData: FormData,
): Promise<OnboardingResult> {
  // Step 1: Verify session.
  const supabase = await createClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: "Unauthorised: valid session required." };
  }

  // Step 2: Validate the enterprise code.
  const enterpriseCode = (
    formData.get("enterprise_code") as string | null
  )?.trim();

  if (!enterpriseCode) {
    return { success: false, error: "Enterprise code is required." };
  }

  // Basic UUID format validation — prevents a malformed string from hitting
  // the database. Does not replace the existence check below.
  const uuidRegex =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (!uuidRegex.test(enterpriseCode)) {
    return {
      success: false,
      error: "Invalid enterprise code format. Please check the code and try again.",
    };
  }

  // Step 3: Verify the organisation exists.
  const { data: org, error: orgError } = await adminClient
    .from("organizations")
    .select("org_id, company_name")
    .eq("org_id", enterpriseCode)
    .single();

  if (orgError || !org) {
    // Return a generic message — do not reveal whether the org_id exists
    // in the system (prevents enumeration attacks).
    return {
      success: false,
      error: "Organisation not found. Please check the enterprise code.",
    };
  }

  // Step 4: Update the user's profile.
  const publicKey = crypto.randomUUID();

  const { error: userError } = await adminClient
    .from("users")
    .update({ org_id: org.org_id, public_key: publicKey })
    .eq("user_id", user.id);

  if (userError) {
    console.error("joinOrganization: update user error:", userError.message);
    return {
      success: false,
      error: "Failed to join organisation. Please try again.",
    };
  }

  // Step 5: Redirect to dashboard.
  redirect("/dashboard");
}
